services:
  devops:
    image: mysite/devops
    build:
      context: ./devops
      dockerfile: Dockerfile

    stdin_open: true
    tty: true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace

    working_dir: /workspace