services:
  devops:
    build:
      context: ..
      dockerfile: devops/Dockerfile

    stdin_open: true
    tty: true

    working_dir: ${PROJECT_ROOT}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PROJECT_ROOT}:${PROJECT_ROOT}