"""delete_slugs

Revision ID: fa24a38cf6c0
Revises: c4c09597d44a
Create Date: 2026-09-08 16:53:42.315748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa24a38cf6c0'
down_revision: Union[str, Sequence[str], None] = 'c4c09597d44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slugs')

def downgrade() -> None:
    """Downgrade schema."""
    pass