"""size_decimal_5_2

Revision ID: 015868780356
Revises: bec71e6a7212
Create Date: 2025-12-01 20:14:12.522088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015868780356'
down_revision: Union[str, Sequence[str], None] = 'bec71e6a7212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tile_sizes', 'height',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.DECIMAL(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('tile_sizes', 'width',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.DECIMAL(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('types', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('types', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tile_sizes', 'width',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)
    op.alter_column('tile_sizes', 'height',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
