"""add_columns_size_id_box_id

Revision ID: 1566e8a4d195
Revises: 015868780356
Create Date: 2025-12-01 20:43:50.277238

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1566e8a4d195"
down_revision: Union[str, Sequence[str], None] = "015868780356"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # 1. Добавляем id колонки
    op.add_column(
        "tile_sizes",
        sa.Column("id", sa.Integer, sa.Identity(start=1, increment=1), nullable=False),
    )

    op.add_column(
        "boxes",
        sa.Column("id", sa.Integer, sa.Identity(start=1, increment=1), nullable=False),
    )

    # 2. Удаляем старые PK с CASCADE (автоматически удалит FK)
    op.execute(sa.text("ALTER TABLE boxes DROP CONSTRAINT boxes_pkey CASCADE"))
    op.execute(
        sa.text("ALTER TABLE tile_sizes DROP CONSTRAINT tile_sizes_pkey CASCADE")
    )

    # 3. СОЗДАЕМ новые PK на id
    op.create_primary_key("boxes_pkey", "boxes", ["id"])
    op.create_primary_key("tile_sizes_pkey", "tile_sizes", ["id"])

    # 5. Добавляем новые колонки в catalog
    op.add_column("catalog", sa.Column("tile_size_id", sa.Integer, nullable=True))
    op.add_column("catalog", sa.Column("box_id", sa.Integer, nullable=True))

    # 6. Заполняем новые колонки
    conn.execute(
        sa.text(
            """
        UPDATE catalog c
        SET box_id = b.id
        FROM boxes b
        WHERE c.box_weight = b.weight 
          AND c.box_area = b.area
    """
        )
    )

    conn.execute(
        sa.text(
            """
        UPDATE catalog c
        SET tile_size_id = ts.id
        FROM tile_sizes ts
        WHERE c.size_length = ts.length 
          AND c.size_height = ts.height
          AND c.size_width = ts.width
    """
        )
    )

    # 7. СОЗДАЕМ новые FK
    op.create_foreign_key("fk_catalog_boxes_id", "catalog", "boxes", ["box_id"], ["id"])
    op.create_foreign_key(
        "fk_catalog_tile_sizes_id", "catalog", "tile_sizes", ["tile_size_id"], ["id"]
    )

    # 8. Делаем NOT NULL
    op.alter_column("catalog", "tile_size_id", nullable=False)
    op.alter_column("catalog", "box_id", nullable=False)

    # 9. Удаляем старые колонки
    op.drop_column("catalog", "box_weight")
    op.drop_column("catalog", "box_area")
    op.drop_column("catalog", "size_length")
    op.drop_column("catalog", "size_height")
    op.drop_column("catalog", "size_width")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
