"""numeric(7_2)_for_sizes

Revision ID: 2ed0d48bed3d
Revises: afe7ffed7716
Create Date: 2025-12-16 22:10:16.032366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed0d48bed3d'
down_revision: Union[str, Sequence[str], None] = 'afe7ffed7716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! #
    op.alter_column('tile_sizes', 'length',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.DECIMAL(precision=7, scale=2),
               existing_nullable=False)
    op.alter_column('tile_sizes', 'height',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.DECIMAL(precision=7, scale=2),
               existing_nullable=False)
    op.alter_column('tile_sizes', 'width',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.DECIMAL(precision=7, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tile_sizes', 'width',
               existing_type=sa.DECIMAL(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('tile_sizes', 'height',
               existing_type=sa.DECIMAL(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('tile_sizes', 'length',
               existing_type=sa.DECIMAL(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
