"""empty message

Revision ID: 629bf51c270c
Revises: 
Create Date: 2025-11-28 20:15:27.516312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629bf51c270c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxes',
    sa.Column('weight', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('area', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('weight', 'area')
    )
    op.create_table('producers',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tile_colors',
    sa.Column('color_name', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('color_name', 'feature_name')
    )
    op.create_table('tile_sizes',
    sa.Column('length', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('height', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('width', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('length', 'height', 'width')
    )
    op.create_table('tile_surface',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color_name', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('size_length', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('size_height', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('size_width', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('box_weight', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('box_area', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('surface_name', sa.String(), nullable=True),
    sa.Column('producer_name', sa.String(), nullable=False),
    sa.Column('boxes_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['box_weight', 'box_area'], ['boxes.weight', 'boxes.area'], ),
    sa.ForeignKeyConstraint(['color_name', 'feature_name'], ['tile_colors.color_name', 'tile_colors.feature_name'], ),
    sa.ForeignKeyConstraint(['producer_name'], ['producers.name'], ),
    sa.ForeignKeyConstraint(['size_length', 'size_height', 'size_width'], ['tile_sizes.length', 'tile_sizes.height', 'tile_sizes.width'], ),
    sa.ForeignKeyConstraint(['surface_name'], ['tile_surface.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tile_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tile_images')
    op.drop_table('catalog')
    op.drop_table('tile_surface')
    op.drop_table('tile_sizes')
    op.drop_table('tile_colors')
    op.drop_table('producers')
    op.drop_table('boxes')
    # ### end Alembic commands ###
