"""squashed initial schema

Revision ID: 68df66e3fe4f
Revises: 
Create Date: 2026-03-28 15:36:15.353554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68df66e3fe4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('area', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weight', 'area')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_path'),
    sa.UniqueConstraint('name')
    )
    op.create_table('producers',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('slugs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name', 'slug')
    )
    op.create_table('tile_colors',
    sa.Column('color_name', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('color_name', 'feature_name')
    )
    op.create_table('tile_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('height', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('width', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('length', 'width', 'height')
    )
    op.create_table('tile_surface',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color_name', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('surface_name', sa.String(), nullable=True),
    sa.Column('producer_name', sa.String(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('boxes_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.ForeignKeyConstraint(['category_name'], ['categories.name'], ),
    sa.ForeignKeyConstraint(['color_name', 'feature_name'], ['tile_colors.color_name', 'tile_colors.feature_name'], ),
    sa.ForeignKeyConstraint(['producer_name'], ['producers.name'], ),
    sa.ForeignKeyConstraint(['size_id'], ['tile_sizes.id'], ),
    sa.ForeignKeyConstraint(['surface_name'], ['tile_surface.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_category',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_name'], ['categories.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'category_name')
    )
    op.create_table('tile_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tile_images')
    op.drop_table('collection_category')
    op.drop_table('catalog')
    op.drop_table('tile_surface')
    op.drop_table('tile_sizes')
    op.drop_table('tile_colors')
    op.drop_table('slugs')
    op.drop_table('producers')
    op.drop_table('collections')
    op.drop_table('categories')
    op.drop_table('boxes')
    op.drop_table('admins')
    # ### end Alembic commands ###
