"""column_name_not_unqic_in_catalog

Revision ID: 693e91c103cc
Revises: 1566e8a4d195
Create Date: 2025-12-02 22:34:53.917116

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "693e91c103cc"
down_revision: Union[str, Sequence[str], None] = "1566e8a4d195"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.drop_constraint(op.f("catalog_name_key"), "catalog", type_="unique")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tile_sizes",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_unique_constraint(
        op.f("catalog_name_key"),
        "catalog",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "boxes",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
