"""add_table_collections

Revision ID: 8ca2e012f82d
Revises: 6173f9f03841
Create Date: 2025-12-08 17:01:27.403035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca2e012f82d'
down_revision: Union[str, Sequence[str], None] = '6173f9f03841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['types.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('image_path')
    )


def downgrade() -> None:
    op.drop_table('collections')
