"""rename_table_types_to_categories

Revision ID: afe7ffed7716
Revises: 7fd95e951603
Create Date: 2025-12-14 11:35:31.427422

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afe7ffed7716"
down_revision: Union[str, Sequence[str], None] = "8ca2e012f82d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column("catalog", column_name="tile_size_id", new_column_name="size_id")
    op.alter_column("catalog", column_name="type_name", new_column_name="category_name")
    op.rename_table("types", "categories")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
