"""add_slugs_table

Revision ID: d0d0439927e9
Revises: 82f83a491aea
Create Date: 2026-02-11 19:21:52.784904

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0d0439927e9"
down_revision: Union[str, Sequence[str], None] = "82f83a491aea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slugs",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name", "slug"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("slugs")
    # ### end Alembic commands ###
