"""drift_check

Revision ID: db61c58b90c1
Revises: fa24a38cf6c0
Create Date: 2026-09-08 17:19:49.119535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db61c58b90c1'
down_revision: Union[str, Sequence[str], None] = 'fa24a38cf6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # TEXT -> VARCHAR
    op.alter_column(
        "categories",
        "name",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )

    # boxes.id: IDENTITY -> обычный sequence + DEFAULT nextval(...)
    op.execute("""
    DO $$
    DECLARE
        old_last_value bigint;
        old_is_called boolean;
    BEGIN
        SELECT last_value, is_called
        INTO old_last_value, old_is_called
        FROM public.boxes_id_seq;

        ALTER TABLE public.boxes
            ALTER COLUMN id DROP IDENTITY;

        CREATE SEQUENCE public.boxes_id_seq
            AS integer
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
            NO CYCLE
            OWNED BY public.boxes.id;

        ALTER TABLE public.boxes
            ALTER COLUMN id
            SET DEFAULT nextval('public.boxes_id_seq'::regclass);

        PERFORM setval(
            'public.boxes_id_seq'::regclass,
            old_last_value,
            old_is_called
        );
    END $$;
    """)

    # tile_sizes.id: IDENTITY -> обычный sequence + DEFAULT nextval(...)
    op.execute("""
    DO $$
    DECLARE
        old_last_value bigint;
        old_is_called boolean;
    BEGIN
        SELECT last_value, is_called
        INTO old_last_value, old_is_called
        FROM public.tile_sizes_id_seq;

        ALTER TABLE public.tile_sizes
            ALTER COLUMN id DROP IDENTITY;

        CREATE SEQUENCE public.tile_sizes_id_seq
            AS integer
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
            NO CYCLE
            OWNED BY public.tile_sizes.id;

        ALTER TABLE public.tile_sizes
            ALTER COLUMN id
            SET DEFAULT nextval('public.tile_sizes_id_seq'::regclass);

        PERFORM setval(
            'public.tile_sizes_id_seq'::regclass,
            old_last_value,
            old_is_called
        );
    END $$;
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tile_sizes', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('categories', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('boxes', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
