"""add_table_tile_type

Revision ID: e92da38a47ec
Revises: 
Create Date: 2025-12-01 17:49:10.348631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92da38a47ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "types",
        sa.Column("name", sa.Text, primary_key=True),
        sa.Column("tile_id", sa.Integer, sa.ForeignKey("catalog.id"))
    )
    conn = op.get_bind()

    parents = conn.execute(sa.text("SELECT id FROM catalog")).fetchall()

    for p in parents:
        conn.execute(
            sa.text("""
            INSERT INTO types(tile_id, name)
            VALUES (:tile_id, :name)
            """),
            {
                "tile_id": p.id,
                "name": "Плитка"
            }
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
