--
-- PostgreSQL database dump
--

\restrict jBOvHjcL1iH3gMhX7tGKfAF8wRIrS8OD3b6zXjMHv9Uy6jOEmkldRQuf2W0Brci

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admins (
    username character varying NOT NULL,
    password character varying NOT NULL
);


ALTER TABLE public.admins OWNER TO postgres;

--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


ALTER TABLE public.alembic_version OWNER TO postgres;

--
-- Name: boxes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.boxes (
    weight numeric(8,2) NOT NULL,
    area numeric(8,2) NOT NULL,
    id integer NOT NULL
);


ALTER TABLE public.boxes OWNER TO postgres;

--
-- Name: boxes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.boxes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.boxes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog (
    id integer NOT NULL,
    name character varying NOT NULL,
    color_name character varying NOT NULL,
    feature_name character varying NOT NULL,
    surface_name character varying,
    producer_name character varying NOT NULL,
    boxes_count integer NOT NULL,
    category_name character varying NOT NULL,
    size_id integer NOT NULL,
    box_id integer NOT NULL
);


ALTER TABLE public.catalog OWNER TO postgres;

--
-- Name: catalog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.catalog_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.catalog_id_seq OWNER TO postgres;

--
-- Name: catalog_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.catalog_id_seq OWNED BY public.catalog.id;


--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    name text NOT NULL
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: collection_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.collection_category (
    category_name character varying NOT NULL,
    collection_id integer NOT NULL
);


ALTER TABLE public.collection_category OWNER TO postgres;

--
-- Name: collections; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.collections (
    id integer NOT NULL,
    name character varying NOT NULL,
    image_path character varying
);


ALTER TABLE public.collections OWNER TO postgres;

--
-- Name: collections_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.collections_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.collections_id_seq OWNER TO postgres;

--
-- Name: collections_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.collections_id_seq OWNED BY public.collections.id;


--
-- Name: producers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producers (
    name character varying NOT NULL
);


ALTER TABLE public.producers OWNER TO postgres;

--
-- Name: slugs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.slugs (
    name character varying NOT NULL,
    slug character varying NOT NULL
);


ALTER TABLE public.slugs OWNER TO postgres;

--
-- Name: tile_colors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tile_colors (
    color_name character varying NOT NULL,
    feature_name character varying NOT NULL
);


ALTER TABLE public.tile_colors OWNER TO postgres;

--
-- Name: tile_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tile_images (
    image_id integer NOT NULL,
    tile_id integer NOT NULL,
    image_path character varying NOT NULL
);


ALTER TABLE public.tile_images OWNER TO postgres;

--
-- Name: tile_images_image_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tile_images_image_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tile_images_image_id_seq OWNER TO postgres;

--
-- Name: tile_images_image_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tile_images_image_id_seq OWNED BY public.tile_images.image_id;


--
-- Name: tile_sizes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tile_sizes (
    length numeric(7,2) NOT NULL,
    height numeric(7,2) NOT NULL,
    width numeric(7,2) NOT NULL,
    id integer NOT NULL
);


ALTER TABLE public.tile_sizes OWNER TO postgres;

--
-- Name: tile_sizes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tile_sizes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tile_sizes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tile_surface; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tile_surface (
    name character varying NOT NULL
);


ALTER TABLE public.tile_surface OWNER TO postgres;

--
-- Name: catalog id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog ALTER COLUMN id SET DEFAULT nextval('public.catalog_id_seq'::regclass);


--
-- Name: collections id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collections ALTER COLUMN id SET DEFAULT nextval('public.collections_id_seq'::regclass);


--
-- Name: tile_images image_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tile_images ALTER COLUMN image_id SET DEFAULT nextval('public.tile_images_image_id_seq'::regclass);


--
-- Data for Name: admins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admins (username, password) FROM stdin;
andy	$2b$12$RCYTQE2Q0bKKmOjn1ojCXeDM687tXlDbsdpTgCF8i83UEa2b49f2e
elena	$2b$12$vGbdOXS83MYs5xz/B6hsLOZW3uSCWTceFqcTiyi29mPKZPIkHErfm
\.


--
-- Data for Name: alembic_version; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.alembic_version (version_num) FROM stdin;
c4c09597d44a
\.


--
-- Data for Name: boxes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.boxes (weight, area, id) FROM stdin;
55.00	555.00	1
25.45	1.60	2
55.00	35.00	3
25.45	35.00	4
29.73	1.60	5
33.13	1.44	6
16.80	1.25	7
33.13	1.25	8
33.30	1.44	9
36.20	1.44	10
23.99	1.39	11
34.38	1.44	12
32.50	1.80	13
17.24	1.23	14
42.00	1.80	15
50.00	2.16	16
32.80	1.44	17
50.00	1.44	18
19.36	1.58	19
\.


--
-- Data for Name: catalog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog (id, name, color_name, feature_name, surface_name, producer_name, boxes_count, category_name, size_id, box_id) FROM stdin;
35	"Андора"	светлая		\N	Axima	32	Плитка облицовочная	2	2
36	"Андора"	светло-коричневая		\N	Axima	32	Плитка облицовочная	2	2
37	"Андора" 	коричневая		\N	Axima	32	Плитка облицовочная	2	2
38	"Андора" геометрия	светло-коричневая		\N	Axima	32	Плитка облицовочная	2	2
39	"Андора" 	коричневая		рельеф	Axima	32	Плитка облицовочная	2	2
40	"Андора"	светлая		\N	Axima	48	Плитка керамическая напольная	3	5
41	"Андора"	коричневая		\N	Axima	48	Плитка керамическая напольная	3	5
42	"Анкара"	верх		\N	Axima	32	Плитка облицовочная	2	2
43	"Анкара" 	низ		\N	Axima	32	Плитка облицовочная	2	2
44	"Анкара" D вставка	светло-бежевая		\N	Axima	32	Плитка облицовочная	2	2
45	"Анкара"	светло-коричневая		\N	Axima	48	Плитка керамическая напольная	3	5
46	"Аризона"	песочная		\N	Axima	32	Плитка облицовочная	2	2
47	"Аризона"	песочная		рельеф	Axima	32	Плитка облицовочная	2	2
48	"Аризона" D вставка	песочная		\N	Axima	32	Плитка облицовочная	2	2
49	"Аризона" геометрия	песочная		\N	Axima	32	Плитка облицовочная	2	2
13	"Авила"	бежевая		\N	Axima	32	Плитка облицовочная	2	2
16	"Авила"	бежевая		рельеф	Axima	32	Плитка облицовочная	2	2
17	"Авила" D вставка	бежевая		\N	Axima	32	Плитка облицовочная	2	2
18	"Альтеа"	светло-серая		\N	Axima	32	Плитка облицовочная	2	2
19	"Альтеа"	светло-серая		рельеф	Axima	32	Плитка облицовочная	2	2
20	"Альтеа"	серая		\N	Axima	32	Плитка облицовочная	2	2
21	"Альтеа"	серая		рельеф	Axima	32	Плитка облицовочная	2	2
22	"Альтеа" D вставка	светло-серая		\N	Axima	32	Плитка облицовочная	2	2
23	"Бурже"	светло-бежевая		\N	Axima	32	Плитка облицовочная	2	2
24	"Бурже"	светло-бежевая		рельеф	Axima	32	Плитка облицовочная	2	2
25	"Леванто"	светлая		\N	Axima	32	Плитка облицовочная	2	2
26	"Леванто"	коричневая		\N	Axima	32	Плитка облицовочная	2	2
27	"Трентино"	светло-бежевая		\N	Axima	32	Плитка облицовочная	2	2
28	"Трентино" D вставка	светло-бежевая		\N	Axima	32	Плитка облицовочная	2	2
29	"Трентино" D1 вставка	светло-бежевая		\N	Axima	32	Плитка облицовочная	2	2
30	"Этна"	светло-серая		\N	Axima	32	Плитка облицовочная	2	2
31	"Этна"	серая		\N	Axima	32	Плитка облицовочная	2	2
33	"Этна" D вставка	серая		\N	Axima	32	Плитка облицовочная	2	2
34	"Этна" D1 вставка	серая		\N	Axima	32	Плитка облицовочная	2	2
50	"Аризона"	песочная		\N	Axima	48	Плитка керамическая напольная	3	5
51	"Венеция"	бежевая		\N	Axima	32	Плитка облицовочная	2	2
52	"Венеция"	светлая		\N	Axima	32	Плитка облицовочная	2	2
53	"Венеция"	серая		\N	Axima	32	Плитка облицовочная	2	2
54	"Венеция" каскад	бежевая		\N	Axima	32	Плитка облицовочная	2	2
55	"Венеция" каскад	серая		\N	Axima	32	Плитка облицовочная	2	2
56	"Венеция" D вставка	бежевая		\N	Axima	32	Плитка облицовочная	2	2
57	"Венеция" D вставка	серая		\N	Axima	32	Плитка облицовочная	2	2
58	"Гавана"	светлая		\N	Axima	32	Плитка облицовочная	2	2
59	"Гавана"	тёмная		\N	Axima	32	Плитка облицовочная	2	2
60	"Гавана" дерево	светло-коричневая		\N	Axima	32	Плитка облицовочная	2	2
61	"Гавана" геометрия	коричневая		\N	Axima	32	Плитка облицовочная	2	2
62	"Гавана" D вставка	коричнево-зелёная		\N	Axima	32	Плитка облицовочная	2	2
63	"Канары"	светлая		\N	Axima	32	Плитка облицовочная	2	2
64	"Канары"	тёмная		\N	Axima	32	Плитка облицовочная	2	2
65	"Канары" цветы	розово-голубая		\N	Axima	32	Плитка облицовочная	2	2
66	"Канары" D вставка	розово-голубая		\N	Axima	32	Плитка облицовочная	2	2
67	"Канары" D1 вставка	розово-голубая		\N	Axima	32	Плитка облицовочная	2	2
68	"Куба"	светло-серая		\N	Axima	32	Плитка облицовочная	2	2
69	"Куба"	серая		\N	Axima	32	Плитка облицовочная	2	2
70	"Куба" D вставка	серо-голубая		\N	Axima	32	Плитка облицовочная	2	2
71	"Куба" D2 вставка	цветная		\N	Axima	32	Плитка облицовочная	2	2
73	"Куба"	светло-серая		\N	Axima	48	Плитка керамическая напольная	3	5
72	"Куба" D1 пано из 3 шт.	цветная		\N	Axima	32	Плитка облицовочная	5	2
74	"Куба"	серая		\N	Axima	48	Плитка керамическая напольная	3	5
75	"Ларго"	белая		\N	Axima	32	Плитка облицовочная	2	2
76	"Ларго"	белая		рельеф	Axima	32	Плитка облицовочная	2	2
77	"Ларго"	серая		рельеф	Axima	32	Плитка облицовочная	2	2
78	"Ларго" дерево	светло-коричневая		\N	Axima	32	Плитка облицовочная	2	2
79	"Луизиана"	светлая		\N	Axima	32	Плитка облицовочная	2	2
80	"Луизиана"	светлая		рельеф	Axima	32	Плитка облицовочная	2	2
81	"Луизиана" D вставка пано из 2шт.	цветная		\N	Axima	32	Плитка облицовочная	6	2
82	"Луизиана" D1 вставка	светлая		\N	Axima	32	Плитка облицовочная	2	2
83	"Луизиана" D2 вставка 	светлая		\N	Axima	32	Плитка облицовочная	2	2
84	"Луизиана"	светлая		\N	Axima	48	Плитка керамическая напольная	3	5
85	"Мартиника"	верх		\N	Axima	32	Плитка облицовочная	2	2
86	"Мартиника"	низ		\N	Axima	32	Плитка облицовочная	2	2
87	"Мартиника" D вставка	бело-серая в полоску		\N	Axima	32	Плитка облицовочная	2	2
88	"Мартиника"	светлая		\N	Axima	48	Плитка керамическая напольная	3	5
89	"Нормандия"	светлая		\N	Axima	32	Плитка облицовочная	2	2
90	"Нормандия"	светлая		рельеф	Axima	32	Плитка облицовочная	2	2
91	"Нормандия"	тёмная		рельеф	Axima	32	Плитка облицовочная	2	2
92	"Нормандия" D вставка	серая		\N	Axima	32	Плитка облицовочная	2	2
93	"Нормандия"	коричневая		\N	Axima	48	Плитка керамическая напольная	3	5
94	"Орлеан"	белая		рельеф	Axima	32	Плитка облицовочная	2	2
95	"Орлеан"	чёрная		\N	Axima	32	Плитка облицовочная	2	2
96	"Орлеан"	чёрная		рельеф	Axima	32	Плитка облицовочная	2	2
97	"Орлеан" геометрия	чёрно-белый		\N	Axima	32	Керамогранит	6	6
98	"Орлеан" квадрат	чёрно-коричневая		\N	Axima	32	Керамогранит	6	6
99	"Орлеан" D вставка	чёрно-белая		\N	Axima	32	Плитка облицовочная	2	2
100	"Ричмонд"	бежевая		\N	Axima	32	Плитка облицовочная	2	2
101	"Ричмонд"	коричневая		\N	Axima	32	Плитка облицовочная	2	2
102	"Ричмонд"	синяя		\N	Axima	32	Плитка облицовочная	2	2
103	"Ричмонд" D вставка	коричневая		\N	Axima	32	Плитка облицовочная	2	2
104	"Ричмонд" D1 вставка	синяя		\N	Axima	32	Плитка облицовочная	2	2
105	"Ричмонд"	бежевая		\N	Axima	48	Плитка керамическая напольная	3	5
106	"Ричмонд"	коричневая		\N	Axima	48	Плитка керамическая напольная	3	5
107	"Санта-Барбара"	светлая		\N	Axima	32	Плитка облицовочная	2	2
108	"Санта-Барбара"	антрацит		\N	Axima	32	Плитка облицовочная	2	2
109	"Санта-Барбара" D вставка	цветная		\N	Axima	32	Плитка облицовочная	2	2
110	"Санта-Барбара" D1 вставка	чёрно-белая		\N	Axima	32	Плитка облицовочная	2	2
111	"Элегия"	верх		\N	Axima	32	Плитка облицовочная	2	2
112	"Элегия"	низ		\N	Axima	32	Плитка облицовочная	2	2
114	"Элегия" D3 вставка	коричневая платина		\N	Axima	32	Плитка облицовочная	2	2
113	"Элегия" D2 вставка	бежевая платина		\N	Axima	32	Плитка облицовочная	2	2
115	"Элегия"	бежевая		\N	Axima	48	Плитка керамическая напольная	3	5
116	"Элегия"	коричневая		\N	Axima	48	Плитка керамическая напольная	3	5
117	"Бордо"	светлая		\N	Axima	45	Плитка облицовочная	7	7
118	"Бордо"	серая		\N	Axima	45	Плитка облицовочная	7	7
119	"Бордо" геометрия	черно-белая		\N	Axima	45	Плитка облицовочная	7	7
120	"Бордо"	антрацит		\N	Axima	45	Плитка облицовочная	7	7
121	"Бордо" D1 вставка	бело-золотая		\N	Axima	45	Плитка облицовочная	7	7
122	"Бордо" D вставка	черно-белая		\N	Axima	45	Плитка облицовочная	7	7
123	"Мальта"	светлая		\N	Axima	45	Плитка облицовочная	7	7
124	"Мальта"	бежевая		\N	Axima	45	Плитка облицовочная	7	7
185	"Марбелья"	белая		\N	Axima	48	Плитка облицовочная	14	14
125	"Мальта"	бежевая		рельеф	Axima	45	Плитка облицовочная	7	7
126	"Мальта"	тёмно-бежевая		\N	Axima	45	Плитка облицовочная	7	7
127	"Мальта" D вставка	светлая		\N	Axima	45	Плитка облицовочная	7	7
128	"Сардиния"	белая		\N	Axima	45	Плитка облицовочная	7	7
129	"Сардиния"	тёмная		\N	Axima	45	Плитка облицовочная	7	7
130	"Сардиния"	узор		\N	Axima	45	Плитка облицовочная	7	7
131	"Андалусия" Флора	светлая		\N	Axima	45	Плитка облицовочная	7	7
132	"Андалусия" 	тёмная		\N	Axima	45	Плитка облицовочная	7	7
133	"Андалусия" D вставка	серая		\N	Axima	45	Плитка облицовочная	7	7
134	"Андалусия" D1 вставка	серая		\N	Axima	45	Плитка облицовочная	7	7
135	"Андалусия" 	серо-золотой		\N	Axima	48	Плитка керамическая напольная	3	5
137	"ALICANTE"	бежевый		\N	Axima	32	Керамогранит	8	9
138	"ALICANTE"	светло-серый		\N	Axima	32	Керамогранит	8	9
139	"ALICANTE"	коричневый		\N	Axima	32	Керамогранит	8	9
141	"ALICANTE"	светло-серый		\N	Axima	30	Керамогранит	9	10
142	"ALICANTE"	бежевый		\N	Axima	30	Керамогранит	9	10
143	"ALICANTE"	коричневый		\N	Axima	30	Керамогранит	9	10
144	"ALICANTE"	бежевая		\N	Axima	46	Плитка керамическая напольная	11	11
145	"ALICANTE"	коричневая		\N	Axima	46	Плитка керамическая напольная	11	11
147	"AMSTERDAM"	кофейный		под дерево	Axima	30	Керамогранит	12	12
146	"AMSTERDAM"	светло-бежевый		под дерево	Axima	30	Керамогранит	12	12
148	"AMSTERDAM"	коричневый		под дерево	Axima	30	Керамогранит	9	12
149	"ARGOS"	серо-коричневый		бетон	Axima	32	Керамогранит	13	13
150	"BALTIMORE"	светло-бежевый		под камень	Axima	32	Керамогранит	13	13
151	"BALTIMORE"	коричневый		под камень	Axima	32	Керамогранит	13	13
152	"Кадис"	низ		\N	Axima	45	Плитка облицовочная	7	7
154	"Кадис" D вставка	серо-голубая		\N	Axima	45	Плитка облицовочная	7	7
153	"Кадис"	верх		\N	Axima	45	Плитка облицовочная	7	7
155	"Кадис"	серая		\N	Axima	48	Плитка керамическая напольная	3	5
156	"Мегаполис"	светло-серая		\N	Axima	45	Плитка облицовочная	7	7
157	"Мегаполис"	серая		\N	Axima	45	Плитка облицовочная	7	7
158	"Мегаполис"	светло-серая мозаика		\N	Axima	45	Плитка облицовочная	7	7
159	"Мегаполис"	серая мозаика		\N	Axima	45	Плитка облицовочная	7	7
160	"Мегаполис"	тёмно-серая мозаика		\N	Axima	45	Плитка облицовочная	7	7
161	"Мегаполис" D вставка	цветы		\N	Axima	45	Плитка облицовочная	7	7
162	"Мегаполис" D1 вставка	цветная		\N	Axima	45	Плитка облицовочная	7	7
163	"Мегаполис"	светло-серая		\N	Axima	48	Плитка керамическая напольная	3	5
164	"Мегаполис"	серая		\N	Axima	48	Плитка керамическая напольная	3	5
165	"Палермо"	светлая		\N	Axima	45	Плитка облицовочная	7	7
166	"Палермо"	тёмная		\N	Axima	45	Плитка облицовочная	7	7
167	"Палермо"	светлая		рельеф	Axima	45	Плитка облицовочная	7	7
168	"Палермо" D вставка	листочки		\N	Axima	45	Плитка облицовочная	7	7
169	"Палермо" D1 вставка	геометрия		\N	Axima	45	Плитка облицовочная	7	7
170	"Палермо"	мозаика		\N	Axima	45	Плитка облицовочная	7	7
171	"Сингапур"	синяя		\N	Axima	45	Плитка облицовочная	7	7
172	"Сингапур" D вставка	синяя		\N	Axima	45	Плитка облицовочная	7	7
173	"Сингапур" D1 вставка	синяя		\N	Axima	45	Плитка облицовочная	7	7
174	"Сингапур" флорида	белая		\N	Axima	45	Плитка облицовочная	7	7
175	"Сингапур" флорида	белая		\N	Axima	48	Плитка керамическая напольная	3	5
176	"Флорида"	белая		\N	Axima	45	Плитка облицовочная	7	7
179	"Флорида"	переходная серая		\N	Axima	45	Плитка облицовочная	7	7
178	"Флорида"	серая		\N	Axima	45	Плитка облицовочная	7	7
180	"Флорида" D вставка	геометрия		\N	Axima	45	Плитка облицовочная	7	7
181	"Флорида"	белая		\N	Axima	48	Плитка керамическая напольная	3	5
182	"Флорида"	серая		\N	Axima	48	Плитка керамическая напольная	3	5
184	"Марбелья"	бежевая		\N	Axima	48	Плитка облицовочная	14	14
183	"Марбелья"	светлое дерево		\N	Axima	48	Плитка облицовочная	14	14
187	"Марбелья"	белая		рельеф	Axima	48	Плитка облицовочная	14	14
188	"Риоса"	светло-серая		\N	Axima	48	Плитка облицовочная	14	14
190	"Риоса" D1 вставка	светло-серая		\N	Axima	48	Плитка облицовочная	14	14
186	"Марбелья"	белая		\N	Axima	48	Плитка облицовочная	14	14
189	"Риоса"	серая		\N	Axima	48	Плитка облицовочная	14	14
191	"Виченца"	светлая		\N	Axima	48	Плитка облицовочная	14	14
192	"Виченца"	тёмная		\N	Axima	48	Плитка облицовочная	14	14
193	"Виченца"	светлая		рельеф	Axima	48	Плитка облицовочная	14	14
194	"Виченца"	геометрия		\N	Axima	48	Плитка облицовочная	14	14
238	"DORTMUND"	серый		мрамор	Axima	30	Керамогранит	15	10
195	"Виченца" Вставка D	серые ромбы		\N	Axima	48	Плитка облицовочная	14	14
196	"Виченца" Вставка D1	серо-голубая		\N	Axima	48	Плитка облицовочная	14	14
197	"Виченца"	светлый мрамор		\N	Axima	48	Плитка керамическая напольная	3	5
198	"Генуя"	светлая		\N	Axima	48	Плитка облицовочная	14	14
199	"Генуя"	пудровая		\N	Axima	48	Плитка облицовочная	14	14
200	"Генуя"	серая		\N	Axima	48	Плитка облицовочная	14	14
201	"Генуя"	геометрия		\N	Axima	48	Плитка облицовочная	14	14
202	"Генуя"	светлая		\N	Axima	48	Плитка керамическая напольная	3	5
203	"Генуя"	серая		\N	Axima	48	Плитка керамическая напольная	3	5
204	"Дорадо"	светло-серая		\N	Axima	48	Плитка облицовочная	14	14
205	"Дорадо"	серая		\N	Axima	48	Плитка облицовочная	14	14
206	"Дорадо" Вставка D	цветная		\N	Axima	48	Плитка облицовочная	14	14
207	"Дорадо" Вставка D1	цветная		\N	Axima	48	Плитка облицовочная	14	14
208	"Дорадо" Вставка D2	геометрия		\N	Axima	48	Плитка облицовочная	14	14
209	"Дорадо" Вставка D3	геометрия		\N	Axima	48	Плитка облицовочная	14	14
210	"Дорадо"	серый камень		\N	Axima	48	Плитка керамическая напольная	3	5
211	"Ибица"	верх		\N	Axima	48	Плитка облицовочная	14	14
212	"Ибица"	низ		\N	Axima	48	Плитка облицовочная	14	14
213	"Ибица" Вставка D	полоски		\N	Axima	48	Плитка облицовочная	14	14
214	"Ибица" Вставка D1	точки		\N	Axima	48	Плитка облицовочная	14	14
215	"Ибица"	серый камень		\N	Axima	48	Плитка керамическая напольная	3	5
216	"Империал"	светло-бежевая		\N	Axima	48	Плитка облицовочная	14	14
217	"Империал"	бежевая		\N	Axima	48	Плитка облицовочная	14	14
218	"Империал" Вставка D	архитектура пано		\N	Axima	48	Плитка облицовочная	14	14
219	"Империал" Вставка D2	архитектура пано		\N	Axima	48	Плитка облицовочная	14	14
220	"Империал" Вставка D3	архитектура пано		\N	Axima	48	Плитка облицовочная	14	14
221	"Империал"	бежевая		\N	Axima	48	Плитка керамическая напольная	3	5
222	"BALTIMORE"	светло-бежевый		под камень	Axima	30	Керамогранит	15	10
223	"BALTIMORE"	коричневый		под камень	Axima	30	Керамогранит	15	10
224	"BERN"	светло-бежевый		бетон	Axima	32	Керамогранит	13	13
225	"BERN"	бежевый		бетон	Axima	32	Керамогранит	13	13
226	"BERN"	серый		бетон	Axima	32	Керамогранит	13	13
227	"BERN"	антрацит		бетон	Axima	32	Керамогранит	13	13
228	"BERN"	светло-бежевый		бетон	Axima	30	Керамогранит	15	10
229	"BERN"	бежевый		бетон	Axima	30	Керамогранит	15	10
230	"BERN"	серый		бетон	Axima	30	Керамогранит	15	10
231	"BERN"	антрацит		бетон	Axima	30	Керамогранит	15	10
232	"CARDIFF"	бежевый		бетон	Axima	30	Керамогранит	15	10
233	"CHELSEA"	светло-серый		бетон	Axima	32	Керамогранит	6	6
234	"CHELSEA"	серый		бетон	Axima	30	Керамогранит	6	6
235	"CHELSEA"	светло-серый		бетон	Axima	30	Керамогранит	15	10
236	"CHELSEA"	серый		бетон	Axima	30	Керамогранит	15	10
237	"DORTMUND"	серый		мрамор	Axima	32	Керамогранит	13	13
239	"EDMONTON"	белый		\N	Axima	32	Керамогранит	8	9
240	"HOUSTON"	серый		под камень	Axima	32	Керамогранит	13	13
241	"HOUSTON"	серый		под камень	Axima	32	Керамогранит	15	10
242	"LIMA"	тёмно-бежевый		под камень	Axima	32	Керамогранит	15	10
245	"PORTLAND"	серый камень		\N	Axima	30	Керамогранит	9	6
246	"REIMS"	бежевый		под камень	Axima	32	Керамогранит	13	13
247	"REIMS"	бежевый		под камень	Axima	32	Керамогранит	15	10
248	"SALVADOR"	светло-коричневый		\N	Axima	32	Керамогранит	13	13
249	"SIENA"	светло-серый		\N	Axima	32	Керамогранит	6	6
250	"SIENA"	серый		\N	Axima	32	Керамогранит	6	6
251	"SIENA"	светло-серый		\N	Axima	30	Керамогранит	15	10
252	"SIENA"	серый		\N	Axima	30	Керамогранит	15	10
253	"SYDNEY"	чёрный		мрамор	Axima	32	Керамогранит	9	10
254	"TIVOLI"	светло-бежевый		\N	Axima	30	Керамогранит	9	10
265	"TOLEDO"	светло-серый		под камень	Axima	32	Керамогранит	6	6
266	"TOLEDO"	серый		под камень	Axima	32	Керамогранит	6	6
267	"TOLEDO"	светло-серый		под камень	Axima	30	Керамогранит	15	10
268	"TOLEDO"	серый		под камень	Axima	30	Керамогранит	15	10
285	"Vizavi" ZA-B12606	светлый мрамор		полированный	Vizavi Ceramica	44	Керамогранит	16	16
286	"Vizavi" ZA-ZA-B12639	коричневый мрамор		полированный	Vizavi Ceramica	44	Керамогранит	16	16
287	"Vizavi" ZA-B12638	серый камень		полированный	Vizavi Ceramica	44	Керамогранит	16	16
274	"Vizavi" ZA-B60332	светлый		матовый	Vizavi Ceramica	30	Керамогранит	6	15
270	"Vizavi" ZA-B60304	белый мрамор		матовый	Vizavi Ceramica	30	Керамогранит	6	15
271	"Vizavi" ZA-B60305	белый мрамор		матовый	Vizavi Ceramica	30	Керамогранит	6	15
272	"Vizavi" ZA-B60315	тёмно-серый камень		матовый	Vizavi Ceramica	30	Керамогранит	6	15
273	"Vizavi" ZA-B60328	серый камень		матовый	Vizavi Ceramica	30	Керамогранит	6	15
269	"Vizavi" ZA-B60303	светло-серый камень		матовый	Vizavi Ceramica	30	Керамогранит	6	15
275	"Vizavi" ZA-B60347	бежевый камень		матовый	Vizavi Ceramica	30	Керамогранит	6	15
277	"Vizavi" ZA-L60911	бежевый бетон		матовый	Vizavi Ceramica	30	Керамогранит	6	15
276	"Vizavi" ZA-L60307	серый мрамор		матовый	Vizavi Ceramica	30	Керамогранит	6	15
278	"Vizavi" ZA-B12503	светло-серый бетон		матовый	Vizavi Ceramica	44	Керамогранит	16	16
279	"Vizavi" ZA-B12514	светло-серый камушек		матовый	Vizavi Ceramica	44	Керамогранит	16	16
280	"Vizavi" ZA-B12517	светло-серый камушек		матовый	Vizavi Ceramica	44	Керамогранит	16	16
281	"Vizavi" ZA-B12909	тёмный камень		матовый	Vizavi Ceramica	44	Керамогранит	16	16
282	"Vizavi" ZA-D12516	тёмный бетон		матовый	Vizavi Ceramica	44	Керамогранит	16	16
283	"Vizavi" ZA-L12512	светло-серый бетон		матовый	Vizavi Ceramica	44	Керамогранит	16	16
284	"Vizavi" ZA-L12719	серый мрамор		матовый	Vizavi Ceramica	44	Керамогранит	16	16
288	"Vizavi" ZA-D12602	светло-серый бетон		полированный	Vizavi Ceramica	44	Керамогранит	16	16
289	"Vizavi" ZA-D12603	светлый бетон		полированный	Vizavi Ceramica	44	Керамогранит	16	16
290	"Vizavi" ZA-D12607	белый мрамор		полированный	Vizavi Ceramica	44	Керамогранит	16	16
291	"Vizavi" ZA-D12608	светло-коричневый мрамор		полированный	Vizavi Ceramica	44	Керамогранит	16	16
292	"Vizavi" ZA-L12604	белый мрамор		полированный	Vizavi Ceramica	44	Керамогранит	16	16
293	"Vizavi" ZA-L12605	белый мрамор		полированный	Vizavi Ceramica	44	Керамогранит	16	16
294	"Vizavi" ZA-L12614	светлый мрамор		полированный	Vizavi Ceramica	44	Керамогранит	16	16
295	"Vizavi" ZA-L12630	тёмный мрамор		полированный	Vizavi Ceramica	44	Керамогранит	16	16
296	"Vizavi" ZA-L12632	тёмный мрамор		полированный	Vizavi Ceramica	44	Керамогранит	16	16
298	GRS 06-01 "Matera" Plumb	черный		матовый	ГраниТаганая	32	Керамогранит	8	17
301	"Matera" GRS06-17 Blanch	бежевый		матовый	ГраниТаганая	32	Керамогранит	8	17
300	"Matera" GRS06-04 Eclipse	тёмно-серый		матовый	ГраниТаганая	32	Керамогранит	8	17
299	"Matera" GRS06-02 Pitch	графит		матовый	ГраниТаганая	32	Керамогранит	8	17
302	"Matera" GRS06-24 Oxide	коричневый		матовый	ГраниТаганая	32	Керамогранит	8	17
303	"Matera" GRS06-26 Earth	светло-коричневый		матовый	ГраниТаганая	32	Керамогранит	8	17
304	"Matera" GRS06-28 Latte	тёмно-бежевый		матовый	ГраниТаганая	32	Керамогранит	8	17
305	GRS07-01 "Madain" Plumb	чёрный		матовый	ГраниТаганая	32	Керамогранит	8	17
306	GRS07-03 "Madain" Carbon	тёмно-серый		матовый	ГраниТаганая	32	Керамогранит	8	17
307	GRS07-06 "Madain" Cloud	серый		матовый	ГраниТаганая	32	Керамогранит	8	17
297	GRS 06-05 "Matera" Steel	серый		матовый	ГраниТаганая	32	Керамогранит	8	17
308	GRS07-17 "Madain" Blanch	светло-серый		матовый	ГраниТаганая	32	Керамогранит	8	17
309	"Madain" GRS07-14 Mittled	серый		карвинг	ГраниТаганая	32	Керамогранит	8	17
310	"Madain" GRS07-15 Grispi	серый		карвинг	ГраниТаганая	32	Керамогранит	8	17
311	"Matera" GRS06-01 Plumb	чёрный		матовый	ГраниТаганая	21	Керамогранит	15	16
312	"Matera" GRS06-02 Pitch	графит		матовый	ГраниТаганая	21	Керамогранит	15	16
313	"Matera" GRS06-04 Eclipse	тёмно-серый		матовый	ГраниТаганая	21	Керамогранит	15	16
314	"Matera" GRS06-05 Steel	серый		матовый	ГраниТаганая	21	Керамогранит	15	16
315	"Matera" GRS06-17 Blanch	бежевый		матовый	ГраниТаганая	21	Керамогранит	15	16
316	"Matera" GRS06-24 Oxide	коричневый		матовый	ГраниТаганая	21	Керамогранит	15	16
317	"Matera" GRS06-26 Earth	светло-коричневый		матовый	ГраниТаганая	21	Керамогранит	15	16
318	"Matera" GRS06-28 Latte	тёмно-бежевый		матовый	ГраниТаганая	21	Керамогранит	15	16
319	GRS07-01 "Madain" Plumb	чёрный		матовый	ГраниТаганая	21	Керамогранит	15	16
320	GRS07-03 "Madain" Carbon	тёмно-серый		матовый	ГраниТаганая	21	Керамогранит	15	16
321	GRS07-06 "Madain" Cloud	серый		матовый	ГраниТаганая	21	Керамогранит	15	16
322	GRS07-17 "Madain" Blanch	светло-серый		матовый	ГраниТаганая	21	Керамогранит	15	16
323	GRS07-14 "Madain" Mittled	серый		карвинг	ГраниТаганая	21	Керамогранит	15	16
324	GRS07-15 "Madain" Grispi	серый		карвинг	ГраниТаганая	21	Керамогранит	15	16
325	GRS 09-29 "Sigiriya" Dairy	светло-серый		матовый	ГраниТаганая	32	Керамогранит	8	17
326	GRS 09-09 "Sigiriya" Clair	серый		матовый	ГраниТаганая	32	Керамогранит	8	17
327	GRS 09-07 "Sigiriya"  Drab	графит		матовый	ГраниТаганая	32	Керамогранит	8	17
328	GRS 09-29 "Sigiriya"  Dairy	светло-серый		матовый	ГраниТаганая	21	Керамогранит	15	16
329	GRS 09-09 "Sigiriya"  Clair	серый		матовый	ГраниТаганая	21	Керамогранит	15	16
330	GRS 09-07 "Sigiriya"  Drab	графит		матовый	ГраниТаганая	21	Керамогранит	15	16
331	"Ellora" GRS01-15 Zircon	белый мрамор		матовый	ГраниТаганая	32	Керамогранит	8	17
332	"Ellora" GRS 01-18 Ashy	серый мрамор		матовый	ГраниТаганая	32	Керамогранит	8	17
333	"Ellora" GRS 01-19 Lotus	белый мрамор		матовый	ГраниТаганая	32	Керамогранит	8	17
334	"Ellora" GRS 01-20 Ivory	белый мрамор		матовый	ГраниТаганая	32	Керамогранит	8	17
335	"Ellora" GRS 01-58 Fire	бежевый мрамор		матовый	ГраниТаганая	32	Керамогранит	8	17
336	"Ellora" GRS 01-15 Zircon	белый мрамор		матовый	ГраниТаганая	21	Керамогранит	15	16
337	"Ellora" GRS 01-18 Ashy	серый мрамор		матовая	ГраниТаганая	21	Керамогранит	15	16
338	"Ellora" GRS 01-19   Lotus	белый мрамор		матовый	ГраниТаганая	21	Керамогранит	15	16
339	"Ellora" GRS 01-20   Ivory	белый мрамор		матовый	ГраниТаганая	21	Керамогранит	15	16
340	"Ellora" GRS 01-58  Fire	бежевый мрамор		матовый	ГраниТаганая	21	Керамогранит	15	16
341	"Gila" GRS 03-16 Tapioca	бежевый камень		матовый	ГраниТаганая	32	Керамогранит	8	17
342	"Gila" GRS 03-28 Latte	тёмно-бежевый камень		матовый	ГраниТаганая	32	Керамогранит	8	18
343	"Gila" GRS 03-16 Tapioca	бежевый камень		матовый	ГраниТаганая	21	Керамогранит	15	16
344	"Gila" GRS 03-28 Latte	тёмно-бежевый камень		матовый	ГраниТаганая	21	Керамогранит	15	16
346	"Lalibela" GRS 04-17 Blanch	бежевый камень		матовая	ГраниТаганая	32	Керамогранит	8	17
345	"Lalibela" GRS 04-07 Drab	серый камень		матовый	ГраниТаганая	32	Керамогранит	8	17
347	"Lalibela" GRS 04-17   Blanch	серый камень		матовый	ГраниТаганая	21	Керамогранит	15	16
348	"Lalibela" GRS04-07  Drab	бежевый камень		матовый	ГраниТаганая	21	Керамогранит	15	16
349	"Simbel" GRS 05-05  Grizzly	тёмно-серый мрамор		матовый	ГраниТаганая	32	Керамогранит	8	17
350	"Simbel" GRS 05-25 Espera	коричневый мрамор		матовый	ГраниТаганая	32	Керамогранит	8	17
351	"Simbel" GRS 05-02 Pitch	чёрный мрамор		матовая	ГраниТаганая	32	Керамогранит	8	17
352	"Simbel" GRS 05-03  Carbon	чёрный мрамор		матовый	ГраниТаганая	32	Керамогранит	8	17
353	"Simbel" GRS 05-05  Grizzly	тёмно-серый мрамор		матовый	ГраниТаганая	21	Керамогранит	15	16
354	"Simbel" GRS 05-25  Espera	коричневый мрамор		матовый	ГраниТаганая	21	Керамогранит	15	16
355	"Simbel" GRS 05-02   Pitch	чёрный мрамор		матовый	ГраниТаганая	21	Керамогранит	15	16
356	"Simbel" GRS 05-03   Carbon	чёрный мрамор		матовый	ГраниТаганая	21	Керамогранит	15	16
357	"Сан-Ремо"	светлая		\N	Axima	48	Плитка облицовочная	14	14
358	"Сан-Ремо"	белая		\N	Axima	48	Плитка облицовочная	14	14
359	"Сан-Ремо"	светло-серая		\N	Axima	48	Плитка облицовочная	14	14
360	"Сан-Ремо"	серая		\N	Axima	48	Плитка облицовочная	14	14
361	"Сан-Ремо"	геометрия		\N	Axima	48	Плитка облицовочная	14	14
362	"Сан-Ремо" вставка D	листочки		\N	Axima	48	Плитка облицовочная	14	14
363	"Сан-Ремо" вставка D1	геометрия		\N	Axima	48	Плитка облицовочная	14	14
364	"Сан-Ремо"	белая		матовая	Axima	46	Плитка керамическая напольная	11	11
365	"Сан-Ремо"	светлая		матовая	Axima	46	Плитка керамическая напольная	11	11
366	"Сан-Ремо"	светло-серая		матовая	Axima	46	Плитка керамическая напольная	11	11
367	"Изабель"	верх		\N	Axima	54	Плитка облицовочная	17	19
368	"Изабель"	низ		\N	Axima	54	Плитка облицовочная	17	19
369	"Изабель" вставка D	бежевая		\N	Axima	54	Плитка облицовочная	17	19
370	"Изабель" вставка D1	бежевая		\N	Axima	54	Плитка облицовочная	17	19
371	"Изабель" вставка D2	бежевая		\N	Axima	54	Плитка облицовочная	17	19
372	"Изабель"	коричневый		матовый	Axima	46	Плитка керамическая напольная	11	11
373	"Монте-Карло"	верх		\N	Axima	54	Плитка облицовочная	17	19
374	"Монте-Карло"	низ		\N	Axima	54	Плитка облицовочная	17	19
375	"Монте-Карло" вставка D	бежевая		\N	Axima	54	Плитка облицовочная	17	19
376	"Монте-Карло" вставка D1	архитектура		\N	Axima	54	Плитка облицовочная	17	19
377	"Монте-Карло" вставка D2	архитектура		\N	Axima	54	Плитка облицовочная	17	19
378	"Монте-Карло"	бежевая		матовая	Axima	46	Плитка керамическая напольная	11	11
379	"Непал"	верх		\N	Axima	54	Плитка облицовочная	17	19
380	"Непал"	низ		\N	Axima	54	Плитка облицовочная	17	19
381	"Непал" Вставка D	бежевая		\N	Axima	54	Плитка облицовочная	17	19
382	"Непал" Вставка D1	бежевая		\N	Axima	54	Плитка облицовочная	17	19
383	"Непал"	коричневая		матовая	Axima	46	Плитка керамическая напольная	11	11
384	"Тулуза"	светлая		\N	Axima	54	Плитка облицовочная	17	19
385	"Тулуза"	тёмная		\N	Axima	54	Плитка облицовочная	17	19
386	"Тулуза" вставка D	серая		\N	Axima	54	Плитка облицовочная	17	19
387	"Тулуза" вставка D1	серая		\N	Axima	54	Плитка облицовочная	17	19
388	"Тулуза" вставка D2	серая		\N	Axima	54	Плитка облицовочная	17	19
389	"Тулуза"	серая		матовая	Axima	48	Плитка керамическая напольная	3	5
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (name) FROM stdin;
Плитка облицовочная
Плитка керамическая напольная
Керамогранит
\.


--
-- Data for Name: collection_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.collection_category (category_name, collection_id) FROM stdin;
Керамогранит	56
Керамогранит	60
Керамогранит	61
Плитка керамическая напольная	22
Плитка керамическая напольная	23
Плитка керамическая напольная	39
Плитка керамическая напольная	42
Плитка керамическая напольная	54
Плитка керамическая напольная	21
Плитка керамическая напольная	43
Плитка керамическая напольная	51
Плитка керамическая напольная	53
Плитка керамическая напольная	28
Плитка керамическая напольная	30
Плитка керамическая напольная	31
Плитка облицовочная	67
Плитка керамическая напольная	67
Плитка облицовочная	68
Керамогранит	57
Керамогранит	59
Плитка облицовочная	47
Плитка облицовочная	19
Плитка облицовочная	36
Плитка облицовочная	20
Плитка облицовочная	49
Плитка облицовочная	26
Плитка облицовочная	37
Плитка облицовочная	38
Керамогранит	8
Плитка облицовочная	52
Плитка облицовочная	39
Плитка облицовочная	55
Плитка облицовочная	54
Плитка облицовочная	27
Плитка облицовочная	42
Плитка облицовочная	29
Плитка облицовочная	46
Плитка облицовочная	35
Плитка облицовочная	44
Плитка облицовочная	25
Плитка облицовочная	45
Керамогранит	9
Плитка облицовочная	48
Плитка облицовочная	40
Плитка облицовочная	50
Керамогранит	10
Плитка облицовочная	21
Плитка облицовочная	51
Керамогранит	11
Плитка облицовочная	28
Плитка облицовочная	34
Плитка облицовочная	53
Плитка облицовочная	43
Плитка облицовочная	24
Плитка облицовочная	41
Плитка облицовочная	22
Плитка облицовочная	23
Керамогранит	16
Керамогранит	14
Плитка облицовочная	30
Плитка облицовочная	31
Плитка облицовочная	32
Плитка облицовочная	33
Керамогранит	12
Керамогранит	13
Керамогранит	15
Керамогранит	17
Керамогранит	18
Керамогранит	1
Керамогранит	2
Керамогранит	3
Керамогранит	4
Керамогранит	5
Керамогранит	6
Керамогранит	7
Керамогранит	62
Керамогранит	63
Керамогранит	64
Плитка облицовочная	66
Плитка керамическая напольная	24
Плитка керамическая напольная	36
Плитка керамическая напольная	44
Плитка керамическая напольная	48
Плитка керамическая напольная	8
Плитка керамическая напольная	34
Плитка керамическая напольная	32
Плитка керамическая напольная	33
Плитка керамическая напольная	66
Плитка керамическая напольная	68
Плитка облицовочная	69
Плитка керамическая напольная	69
Плитка облицовочная	70
Плитка керамическая напольная	70
\.


--
-- Data for Name: collections; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.collections (id, name, image_path) FROM stdin;
56	Vizavi	static/images/base/collections/vizavi.jpg
57	Matera	static/images/base/collections/matera.webp
59	Sigiriya	static/images/base/collections/sigiriya.webp
60	Madain	static/images/base/collections/madain.webp
61	Ellora	static/images/base/collections/ellora.webp
62	Gila	static/images/base/collections/gila.webp
63	Lalibela	static/images/base/collections/lalibela.webp
64	Simbel	static/images/base/collections/simbel.webp
66	Сан-Ремо	static/images/base/collections/san-remo.jpg
67	Изабель	static/images/base/collections/izabel.jpg
68	Монте-Карло	static/images/base/collections/monte-karlo.jpg
69	Непал	static/images/base/collections/nepal.jpg
70	Тулуза	static/images/base/collections/tuluza.jpg
1	PORTLAND	static/images/base/collections/portland.png
2	REIMS	static/images/base/collections/reims.jpg
3	SALVADOR	static/images/base/collections/salvador.jpg
4	SIENA	static/images/base/collections/siena.jpg
5	SYDNEY	static/images/base/collections/sydney.jpg
6	TIVOLI	static/images/base/collections/tivoli.jpg
7	TOLEDO	static/images/base/collections/toledo.jpg
8	ALICANTE	static/images/base/collections/alicante.jpg
9	AMSTERDAM	static/images/base/collections/amsterdam.jpg
10	ARGOS	static/images/base/collections/argos.jpg
11	BALTIMORE	static/images/base/collections/baltimore.jpg
12	BERN	static/images/base/collections/bern.jpg
13	CARDIFF	static/images/base/collections/cardiff.jpg
14	CHELSEA	static/images/base/collections/chelsea.jpg
15	DORTMUND	static/images/base/collections/dortmund.jpg
16	EDMONTON	static/images/base/collections/edmonton.jpg
17	HOUSTON	static/images/base/collections/houston.jpg
18	LIMA	static/images/base/collections/lima.jpg
19	Авила	static/images/base/collections/avila.jpg
20	Альтеа	static/images/base/collections/altea.jpg
21	Андалусия	static/images/base/collections/andalusiia.jpg
22	Андора	static/images/base/collections/andora.jpg
23	Анкара	static/images/base/collections/ankara.jpg
24	Аризона	static/images/base/collections/arizona.jpg
25	Бордо	static/images/base/collections/bordo.jpg
26	Бурже	static/images/base/collections/burzhe.jpg
27	Венеция	static/images/base/collections/venetsiia.jpg
28	Виченца	static/images/base/collections/vichentsa.jpg
29	Гавана	static/images/base/collections/gavana.jpg
30	Генуя	static/images/base/collections/genuia.jpg
31	Дорадо	static/images/base/collections/dorado.jpg
32	Ибица	static/images/base/collections/ibitsa.jpg
33	Империал	static/images/base/collections/imperial.jpg
34	Кадис	static/images/base/collections/kadis.jpg
35	Канары	static/images/base/collections/kanary.jpg
36	Куба	static/images/base/collections/kuba.jpg
37	Ларго	static/images/base/collections/largo.jpg
38	Леванто	static/images/base/collections/levanto.jpg
39	Луизиана	static/images/base/collections/luiziana.jpg
40	Мальта	static/images/base/collections/malta.jpg
41	Марбелья	static/images/base/collections/marbelia.jpg
42	Мартиника	static/images/base/collections/martinika.jpg
43	Мегаполис	static/images/base/collections/megapolis.jpg
44	Нормандия	static/images/base/collections/normandiia.jpg
45	Орлеан	static/images/base/collections/orlean.jpg
46	Палермо	static/images/base/collections/palermo.jpg
47	Риоса	static/images/base/collections/riosa.jpg
48	Ричмонд	static/images/base/collections/richmond.jpg
49	Санта-Барбара	static/images/base/collections/santa-barbara.jpg
50	Сардиния	static/images/base/collections/sardiniia.jpg
51	Сингапур	static/images/base/collections/singapur.jpg
52	Трентино	static/images/base/collections/trentino.jpg
53	Флорида	static/images/base/collections/florida.jpg
54	Элегия	static/images/base/collections/elegiia.jpg
55	Этна	static/images/base/collections/etna.jpg
\.


--
-- Data for Name: producers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producers (name) FROM stdin;
Axima
Vizavi Ceramica
ГраниТаганая
\.


--
-- Data for Name: slugs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.slugs (name, slug) FROM stdin;
Vizavi	vizavi
Matera	matera
Sigiriya	sigiriya
Madain	madain
Ellora	ellora
Gila	gila
Lalibela	lalibela
Simbel	simbel
Сан-Ремо	san-remo
Изабель	izabel
Монте-Карло	monte-karlo
Непал	nepal
Тулуза	tuluza
Ибица	ibitsa
Трентино	trentino
TOLEDO	toledo
Венеция	venetsiia
Керамогранит	keramogranit
Аризона	arizona
Санта-Барбара	santa-barbara
Генуя	genuia
Орлеан	orlean
CARDIFF	cardiff
Флорида	florida
Луизиана	luiziana
Палермо	palermo
PORTLAND	portland
AMSTERDAM	amsterdam
Куба	kuba
SYDNEY	sydney
LIMA	lima
CHELSEA	chelsea
Канары	kanary
SALVADOR	salvador
Андора	andora
Нормандия	normandiia
Сардиния	sardiniia
Этна	etna
TIVOLI	tivoli
Дорадо	dorado
Империал	imperial
Авила	avila
REIMS	reims
BALTIMORE	baltimore
ARGOS	argos
EDMONTON	edmonton
Мальта	malta
Мегаполис	megapolis
Ларго	largo
Альтеа	altea
Гавана	gavana
Мартиника	martinika
DORTMUND	dortmund
Бордо	bordo
Марбелья	marbelia
Анкара	ankara
Плитка керамическая напольная	plitka-keramicheskaia-napolnaia
Ричмонд	richmond
Леванто	levanto
Элегия	elegiia
ALICANTE	alicante
Кадис	kadis
HOUSTON	houston
Сингапур	singapur
Риоса	riosa
Плитка облицовочная	plitka-oblitsovochnaia
BERN	bern
Бурже	burzhe
Виченца	vichentsa
Андалусия	andalusiia
SIENA	siena
\.


--
-- Data for Name: tile_colors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tile_colors (color_name, feature_name) FROM stdin;
бежевая	
светло-серая	
серая	
светло-бежевая	
светлая	
коричневая	
светло-коричневая	
верх	
низ	
песочная	
тёмная	
коричнево-зелёная	
розово-голубая	
серо-голубая	
цветная	
белая	
бело-серая в полоску	
чёрная	
чёрно-белый	
чёрно-коричневая	
чёрно-белая	
синяя	
антрацит	
коричневая платина	
бежевая платина	
черно-белая	
бело-золотая	
тёмно-бежевая	
узор	
серо-золотой	
бежевый	
светло-серый	
коричневый	
кофейный	
светло-бежевый	
серо-коричневый	
светло-серая мозаика	
серая мозаика	
тёмно-серая мозаика	
цветы	
листочки	
геометрия	
мозаика	
переходная серая	
бежевая доска	
светлое дерево	
серые ромбы	
светлый мрамор	
пудровая	
серый камень	
полоски	
точки	
архитектура пано	
серый	
белый	
тёмно-бежевый	
светло-коричневый	
чёрный	
белый мрамор	
тёмно-серый камень	
светло-серый камень	
светлый	
бежевый камень	
серый мрамор	
бежевый бетон	
светло-серый бетон	
светло-серый камушек	
тёмный камень	
тёмный бетон	
мрамор	
коричневый мрамор	
светлый бетон	
светло-коричневый мрамор	
тёмный мрамор	
черный	
графит	
тёмно-серый	
бежевый мрамор	
тёмно-бежевый камень	
тёмно-серый мрамор	
чёрный мрамор	
архитектура	
\.


--
-- Data for Name: tile_images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tile_images (image_id, tile_id, image_path) FROM stdin;
18	20	static/images/base/products/419ae2ec81a3f5c9f5273d4e21637d96.jpg
14	16	static/images/base/products/00936221f8496b022cb9198ee6cbb040.jpg
15	17	static/images/base/products/78c61ef33182fc914f32b42021e2c0ad.jpg
21	23	static/images/base/products/b1cfc7459a3c33e81bf5d1c4d3b210f9.jpg
22	24	static/images/base/products/13658f0737434b976b364c66a54651d1.jpg
25	27	static/images/base/products/909c605e5b21ac9cadc598d856301afe.jpg
26	28	static/images/base/products/d6ffef34852623a7e6d51f11e110e225.jpg
28	30	static/images/base/products/735356251fdf65426bdfbb7c08825372.jpg
29	31	static/images/base/products/611888c911d18f2378a09702208ded4d.jpg
33	35	static/images/base/products/68af898e4317389b4183b749ca069934.jpg
34	36	static/images/base/products/a1fa88c4186dfb49b7eb6c292972177e.jpg
36	38	static/images/base/products/8ddb20cd11572d7235a9d7e581da11d8.jpg
37	39	static/images/base/products/7961e84f191b93e7c8eaefc8d6042c2d.jpg
40	42	static/images/base/products/1a7ec4f82476d389753ed94488624c4c.jpg
41	43	static/images/base/products/70f536de4d9889106aa1ef3c3aeae74a.jpg
43	45	static/images/base/products/f5a111ce0a7dd37e05d40038440bc0b3.jpg
45	47	static/images/base/products/ec394602210ace3bef2cdddc14f2dc54.jpg
47	49	static/images/base/products/4c7eac8e4ee57267f50a7ac22fd34f8b.png
48	50	static/images/base/products/52f368a419a3bb1c16d9c640c67712d9.png
50	52	static/images/base/products/a98f970fbc67899123a2e5826c3f0828.jpg
52	54	static/images/base/products/3e4a1151400212efe9b0cae2c5909253.jpg
54	56	static/images/base/products/738496e749f8920eb7ae29288cea07e3.jpg
55	57	static/images/base/products/18732ce595e6d876d5c7b7fa51b6cbcd.jpg
58	60	static/images/base/products/a27ac602a7f466454ee3c9e3b46cc072.jpg
59	61	static/images/base/products/64617331a9868e5125055bbf8b182bc5.jpg
61	63	static/images/base/products/a29d0928c50eb7cdec66c197bc810459.jpg
62	64	static/images/base/products/5812045e15d833e2cd03058a73de2af2.jpg
65	67	static/images/base/products/e4a5ab90d774b6fb41c57611f799398a.jpg
66	68	static/images/base/products/7fc1dcf4e73d03cd0266e7a59f731e29.jpg
68	70	static/images/base/products/b5b18da02b886c162620479d98bc1435.jpg
69	71	static/images/base/products/bf5c524951e65006f2c11168f1f3d4f8.jpg
72	74	static/images/base/products/d41623e79464535136809e489241c818.jpg
73	75	static/images/base/products/8410fa9759cd77dd853ea5062d7ae45b.jpg
75	77	static/images/base/products/96e34847f2e3433d104edb1f4db136d1.jpg
77	79	static/images/base/products/80943c15680db366266fd32124ae54ff.jpg
79	81	static/images/base/products/7f083ae7e1d16be76cc6d3115f349e7a.png
80	82	static/images/base/products/278f93afd86630b41ad046a3cc27689a.jpg
83	85	static/images/base/products/c6e3ec06e0a75877d45ae778f161a433.jpg
84	86	static/images/base/products/da6bbe8d11102490b38a8a7ddfa7e803.jpg
86	88	static/images/base/products/d61390bf053cda2b0db40e2f98b3418c.jpg
87	89	static/images/base/products/b14bbae408c5d04918aed7f46acf5549.jpg
90	92	static/images/base/products/2e1c39db5e9fb7ffbdab1ff6b1c8e0a0.jpg
91	93	static/images/base/products/bf9e7a3976e054b131b3f55b378fd5dc.jpg
93	95	static/images/base/products/21a6732f4ed8b64f43fd9e2c448dedd4.jpg
94	96	static/images/base/products/947e5d84c95aef12db91d350bce22048.jpg
97	99	static/images/base/products/5d535316ae863d04363e5f15e1ad3d51.jpg
98	100	static/images/base/products/321b1aa5ba505b23c56478b05d4ea149.jpg
100	102	static/images/base/products/4b349678d82e5cd2ba08432294006249.jpg
102	104	static/images/base/products/45d2b69ca6f4f0a961c18aa38504940b.jpg
104	106	static/images/base/products/fa01e949d9f38fc7ce87b0ff3e43d1ae.jpg
105	107	static/images/base/products/5075bb78465a0b640ee716e14885e00a.jpg
107	109	static/images/base/products/d5f99ea73c0d09f5a4de3ddc26b23f74.jpg
109	111	static/images/base/products/610f774385e866814a8814eb7606cd3e.jpg
111	113	static/images/base/products/5c403e4602907ba1a3f1e404ccc67b32.jpg
112	114	static/images/base/products/be16f8b33148dcbad948006137a0c903.jpg
115	117	static/images/base/products/8a85dac6d088834e7a3109afd8b7f996.jpg
116	118	static/images/base/products/8be0841130f04b25cea1d824c3e48245.jpg
118	120	static/images/base/products/a6219a1221a4dcbb9b1b8eaafba76f22.jpg
119	121	static/images/base/products/04082586aa5e5547100ff06e42e4eeb1.jpg
122	124	static/images/base/products/032e262168245743da806f6fafb92f60.jpg
123	125	static/images/base/products/c9cad84520ac6feee1061ba693ba0f54.png
125	127	static/images/base/products/7403fd825d687b717f8581ed1b1ff0fd.png
126	128	static/images/base/products/cef938e177b26cae12b017b5dca42a18.jpg
129	131	static/images/base/products/13cc79e847480fc172674ff91996c43a.jpg
130	132	static/images/base/products/ec1ad17111ac6caeb6ae62f5c24d646d.jpg
24	26	static/images/base/products/d4c662d5df5c86c14d88bf94f72874e7.jpg
32	34	static/images/base/products/74ec92f832f0d2a28b4d48c5fd59d334.jpg
44	46	static/images/base/products/806be50291f121b44e3bc9364aa92dcf.jpg
51	53	static/images/base/products/dc36248932665e654721dc96846e11e2.jpg
63	65	static/images/base/products/a99f30b071b3ae3c946c2f52728497c7.jpg
70	72	static/images/base/products/6938d0621f38b55eb06f814b654337fd.jpg
82	84	static/images/base/products/f56dc3a892fc83b05e5947b1c5ece189.jpg
95	97	static/images/base/products/ca2d338c68a63d7d8cafcb9ff324d0d5.jpg
101	103	static/images/base/products/4a9d40f0b8fd0eaa1639d68c57ad2809.jpg
114	116	static/images/base/products/cf4236024b102988413b96f53c9e5688.jpg
120	122	static/images/base/products/f854967146f7c419ba169048f93c9d3c.jpg
132	134	static/images/base/products/5d7f9624116ae0c244248c42547ee261.jpg
133	135	static/images/base/products/2b1c7712bc386fc1fae008d9cdd6147a.jpg
136	138	static/images/base/products/08139c6b0220f249f2b88a9457fc2669.jpg
137	139	static/images/base/products/409df4aad9d69b27ccfb475cd6277e43.jpg
140	142	static/images/base/products/4a8c950ad6d8bddfbb2da3fd02083324.jpg
141	143	static/images/base/products/71e03f8c12712fffe0c5b79a6283bed5.jpg
143	145	static/images/base/products/ea7e3e7397b17ba6715ba300590b1f55.jpg
144	146	static/images/base/products/64d02dcbab917f08fe7941a4255cb976.jpg
146	148	static/images/base/products/1dee08a6e0510ef1d4c321d093e4f821.jpg
147	149	static/images/base/products/d9663240ca063482c938d2eb71cc01d7.jpg
149	151	static/images/base/products/b4f73f349d929decf271d7523157c115.jpg
150	152	static/images/base/products/aeedf3eb580cc71fdedd26bb3e74175a.jpg
152	154	static/images/base/products/0a67fd9b7f230bacc26ffcb75ff7899b.jpg
153	155	static/images/base/products/a0609bb72962395632e82c3feed3117d.jpg
155	157	static/images/base/products/56302eac09b18f65f0f1cc832d0366de.jpg
156	158	static/images/base/products/5e0a4398150d15aea3bf6a9bccfdc8e7.jpg
158	160	static/images/base/products/1395f17c47e5a18864a3698cb07fdeac.jpg
159	161	static/images/base/products/a233a22c64920e83eff602da89df9d1f.jpg
161	163	static/images/base/products/1752ee853af33f166b3bb075e9496382.jpg
162	164	static/images/base/products/3cb6cef5b5bbe6fade3cd71fb67e62a1.jpg
164	166	static/images/base/products/217b4671fae04b7626fffff2cb955dd3.jpg
165	167	static/images/base/products/5038fdf25905e67395dd6b5e893e6c3e.jpg
167	169	static/images/base/products/f0d5e2c3bc4bd182c9694eee1fb6276c.jpg
168	170	static/images/base/products/b2314022e31b6aa0520cd1e66f9d6c96.jpg
170	172	static/images/base/products/d6f301f1f2c0644ebb42dd4d2e3df8ec.jpg
171	173	static/images/base/products/c8f04d2e729e1a99d2d7a06c8bc39364.jpg
173	175	static/images/base/products/5c9147ae8191844cce6061d6266678dc.jpg
174	176	static/images/base/products/058d85cd96c398c91f0c496d8ca85c54.jpg
177	179	static/images/base/products/5c136a57f263e0493c6f653ac79ac474.jpg
178	180	static/images/base/products/fb87b9ab2cff4e1423aeec08d8bbbefb.jpg
180	182	static/images/base/products/aa831a957c65dccf230c6fb11dc36bab.jpg
181	183	static/images/base/products/cef32058d64edf8cc0e98d5c89bc465f.jpg
183	185	static/images/base/products/459c93fd651c40741f25a6f8feb63c6f.jpg
184	186	static/images/base/products/459c93fd651c40741f25a6f8feb63c6f.jpg
186	188	static/images/base/products/140b9d1e11d82534f63b832f145bbef0.jpg
187	189	static/images/base/products/139ebe6f85f93b9fb1de80eb76b23cfb.jpg
205	207	static/images/base/products/828325af2af7983c7eb8d664944711a2.jpg
13	13	static/images/base/products/fb2e5521f988d761d3164ef8a2398071.jpg
189	191	static/images/base/products/78bd2b83aa9d67d3145ff1f3b519ed2e.jpg
190	192	static/images/base/products/de1ed63f25ed1f2ad41f37f522f6e20f.jpg
192	194	static/images/base/products/9b5d5ac2fc65680d1db1abac76d19759.jpg
193	195	static/images/base/products/07f98ede2f04fd353255d9f8154a9930.jpg
195	197	static/images/base/products/0f067237c927d987b5a1d7560bc6a5e5.jpg
196	198	static/images/base/products/e6f531bdf9930a761c189dc596ab6fd1.jpg
17	19	static/images/base/products/0288f5576735d00e214d4344ed915854.jpg
198	200	static/images/base/products/b67290b8a42276faf0169ff3c9832c21.jpg
200	202	static/images/base/products/ad907a48f39b76fa9ed346f1338525ba.jpg
201	203	static/images/base/products/85b80e4e4d417d9dc92f0374283ab212.jpg
203	205	static/images/base/products/d47eab6094cba0c3ea1e0387a174fd04.jpg
204	206	static/images/base/products/aa57bb6746690e91085d211e15612628.jpg
208	210	static/images/base/products/de8d66d0487ffdf2fbdee605cfba707c.jpg
209	211	static/images/base/products/0d894c1656007848460503217ef6be5e.jpg
211	213	static/images/base/products/769ba7cd9cd2cb2f8bfca101b82d6d9c.jpg
212	214	static/images/base/products/adae416c5f09cb5c3e9fd988b70fd9dd.jpg
214	216	static/images/base/products/6855af3b5e31f904497c638fce94d445.jpg
215	217	static/images/base/products/f6456e1e75443f2c5fb32122460e20ec.jpg
217	219	static/images/base/products/e89a25394c2a84c5eca71e1a0fa215b8.jpg
218	220	static/images/base/products/b97509ce608cc6e326f6b28ed800d6e1.jpg
220	222	static/images/base/products/1a2598402cde3e1019c3dc37398c7f25.jpg
221	223	static/images/base/products/ff04a2df827304edcf91410a308d564a.jpg
226	228	static/images/base/products/4882fc0d78989f44ae17db9409ee17d2.jpg
227	229	static/images/base/products/a2ef6960b18ee0cd65762eeab51ca8fb.jpg
229	231	static/images/base/products/4f9d63987d159a743d101cdc7a94d886.jpg
230	232	static/images/base/products/d0e6ff2bfa7904a096dae1a9b9f3de03.jpg
233	235	static/images/base/products/bb1dec242d18890a207da2e4b9a67b1c.jpg
234	236	static/images/base/products/c9a513e3467e44e78fb319966dfd14b3.jpg
223	225	static/images/base/products/78ca84760d1be558449d4cc5f11df888.jpg
231	233	static/images/base/products/b9a39cd6e19cd20b41f50fd68cff5e04.jpg
235	237	static/images/base/products/4196290a6d42ac7249751669481b2bba.jpg
237	239	static/images/base/products/fd03aa43099aeda0cb1539f8d14e20f4.jpg
238	240	static/images/base/products/21199b63ff09742eb727f5ff6d848b1c.jpg
240	242	static/images/base/products/f35a6c0d42e0692925c306482238102d.jpg
243	245	static/images/base/products/acc4b2e6174a72891dd777343e41f849.png
245	247	static/images/base/products/7169e28d788510cebd0a9ec1f76e8c9c.jpg
246	248	static/images/base/products/60acf69071326063cc331f022117f401.jpg
248	250	static/images/base/products/3911881d15d00bb18c9ecd82bcdddedf.jpg
249	251	static/images/base/products/5539124178b35f287507f8c2230f5a04.jpg
251	253	static/images/base/products/c387a2089f327079bc9a2a68d4c251a9.jpg
252	254	static/images/base/products/51058176c4b122c8a3565bb0867457f0.jpg
264	266	static/images/base/products/4b2f5f05509254d7c3c7024977c82866.jpg
265	267	static/images/base/products/8f691ec3a6cd7cdda57a23bf571fa600.jpg
267	269	static/images/base/products/61d89499a05c5481d0d36664f504d784.webp
268	270	static/images/base/products/1c4c4ebeb32b8f4de87fa72554473b51.webp
270	272	static/images/base/products/7d47fa61bc22ee7d9b1719fb3c17a6ed.webp
271	273	static/images/base/products/1e44b291b9b67562ceb4009b142f2dda.webp
273	275	static/images/base/products/182534080c23e41bd58ff4e6bbcafaa0.webp
274	276	static/images/base/products/c22e7950c19369771eca7b47899a4e77.webp
276	278	static/images/base/products/5365d062f3a3d39f4ec50f25ebdf3053.webp
277	279	static/images/base/products/af796fb578d49c126a04b597a7849b22.webp
279	281	static/images/base/products/c76b848b2700e0560ea9561cf5f645bb.webp
280	282	static/images/base/products/c72306b9dccd4341298d210dbabe6306.webp
282	284	static/images/base/products/5939081e54d6ea1b7836b0f0d76354fd.webp
283	285	static/images/base/products/3d3d26a12780ba848ca3e675fada04ad.webp
285	287	static/images/base/products/6e0e9b9bcb3799fe775542a96af8beae.webp
286	288	static/images/base/products/72042bdddd512116d095f57e2a2f61ca.webp
288	290	static/images/base/products/973842bcb98c5b19ecd134542af1f7c9.webp
289	291	static/images/base/products/9454cac1d5fb426043d6a44edc1f26bb.webp
291	293	static/images/base/products/38d7074bf417aa2f5e210180e8db1452.webp
292	294	static/images/base/products/a6ff398e0c938ec18a84842eba5b621a.webp
294	296	static/images/base/products/9c64c052beaf7799d636fb5f056324b3.webp
295	297	static/images/base/products/c41928d0ccea6a9ca1828bbb1bbd34ae.webp
297	299	static/images/base/products/e3a13afe0f1a94db148e97aa815434b3.webp
298	300	static/images/base/products/577bff8d2557c1bf3df7afaa9ba7c0e2.webp
300	302	static/images/base/products/e4f01915319df02618ee5b15568d1dd9.webp
301	303	static/images/base/products/5fd4aeb9ca60b0b054c68b36596ca873.webp
303	305	static/images/base/products/e7cc9dc0d64a69364da14cf9ef1d4672.jpg
304	306	static/images/base/products/a3a48763a0d89f2129cd8e8cc2b6316b.webp
306	308	static/images/base/products/1ecca1fb5916197aec0975bbce0d96fa.webp
307	309	static/images/base/products/a86d5cef94f3196bbb452af9b3c6e07a.webp
309	311	static/images/base/products/bd03a912202a2d3ee52ea00c330bf9ab.webp
310	312	static/images/base/products/f449f5a915cd54544022580dd7cd285c.webp
312	314	static/images/base/products/7a0b8b5c0531c70552e9d43a348f52c8.webp
313	315	static/images/base/products/100054cf2fd4c89ed8c125bf0779f5d9.webp
315	317	static/images/base/products/f6f865865c73c225aed80a79256e6f5c.webp
316	318	static/images/base/products/7cea4105c86edfda1a7fc4de93e6eba5.webp
318	320	static/images/base/products/dce6af1fdbb8e26b93abd915342f4f88.webp
319	321	static/images/base/products/70b54ee2be82a918ccb34f6aef87db89.webp
321	323	static/images/base/products/40fc57eaff3d2a5778ef86cd1a9f1c5d.webp
322	324	static/images/base/products/e2989a2796636c2f4196bbbbc1f79637.webp
324	326	static/images/base/products/07140473b413a0e102a391cc596b68cc.webp
325	327	static/images/base/products/eeefad90a813c058a47d1254fea35c33.webp
327	329	static/images/base/products/67104cc00f3f251c6b979b479a19434d.webp
328	330	static/images/base/products/b16bbabcd2c8e328ae625bab87320ca2.webp
330	332	static/images/base/products/3cd6b4e807d9606941d883b6d29bdbd8.webp
331	333	static/images/base/products/e4b06a8ec5859cc5d646004c7bd10ef0.webp
333	335	static/images/base/products/1d19fe4ef3262c67cdf5d6c606f10079.webp
334	336	static/images/base/products/b68a24552d519861a7351be92066f398.webp
336	338	static/images/base/products/76c2f7b168a88a5c9913e9b660bcc836.webp
337	339	static/images/base/products/d2ef854f384ae42efc3d2df8913fa2a3.webp
339	341	static/images/base/products/8d76cb7680814e864c32f3edde8674fe.webp
340	342	static/images/base/products/54935ee0315719c01225983a1389a8fe.webp
342	344	static/images/base/products/6757c309d8cd79a34018913dc849d758.webp
343	345	static/images/base/products/76eb401a8a45e23d840700b02f699ee1.webp
345	347	static/images/base/products/c1d1ec353a5bacf914f785c3cefde6e0.webp
346	348	static/images/base/products/df52c217d3d15e59f9a593d1a851a39d.webp
348	350	static/images/base/products/eebe64e16c1972c7c8b6170c921d3d98.webp
349	351	static/images/base/products/92f92ca64eb896ff2ac01a70f2e85288.webp
16	18	static/images/base/products/96a3adc5e6455731693b71604e224816.jpg
19	21	static/images/base/products/e5dd5b7c5e50f4f466b08fb6fb687926.jpg
20	22	static/images/base/products/51e5f6943a9e1e0e5ecd4fd67eb09dd9.jpg
23	25	static/images/base/products/23716b4e29594bc48d060dabedead63f.jpg
27	29	static/images/base/products/770bd27226e7c092977e7c8441cba5f8.jpg
31	33	static/images/base/products/3eb3965b97c5dbd0c28c884add9b706a.jpg
35	37	static/images/base/products/b5e76b0b3e6ff35bb880f84c863497a7.jpg
39	41	static/images/base/products/8f0ab456d71b4791514c8152e062aa90.jpg
42	44	static/images/base/products/1e5437b2a1fd521cff3d60db3f543468.jpg
46	48	static/images/base/products/2b40f8f09157f69d10ec6f7870877da1.jpg
49	51	static/images/base/products/8d0114848c02c2f8ef7584e624aa1c29.jpg
53	55	static/images/base/products/36ef3ce09735b0eef5450b6072c0a186.jpg
56	58	static/images/base/products/c129db7be589b15a879ac2edca4adf91.jpg
60	62	static/images/base/products/7a9cfb6922a7d3e1ff48116e408c60f6.jpg
64	66	static/images/base/products/095bb5911540c71bae3aa4588d3958b2.jpg
67	69	static/images/base/products/9f9c5fc27f81667f786280770a68ae2c.jpg
71	73	static/images/base/products/6e88f318419b8ca4942a36e2b07b2b0f.png
74	76	static/images/base/products/e5f0c2307a8739e3d1945c8895a6b428.png
78	80	static/images/base/products/ca490db32efbbad7120c2eb651c077e2.jpg
81	83	static/images/base/products/81ea4d8f0f86bcd1723786b0a2425c91.jpg
85	87	static/images/base/products/99bab6a0d31c7357c7c97a04f046a4d6.jpg
88	90	static/images/base/products/60eb32c04ed0aa81c294823dec138b5d.jpg
92	94	static/images/base/products/4588df010af13584318e5a7e399db22f.jpg
96	98	static/images/base/products/6fc13313ecb74eea43c852d58bcd59d3.jpg
99	101	static/images/base/products/2d088a95e9876d674da4dc0d9b27855e.jpg
103	105	static/images/base/products/61bc23c5d1b176e553fe810d4f99695d.jpg
106	108	static/images/base/products/3eb576b28b904b38414364ae82484229.jpg
110	112	static/images/base/products/515c0ccf5bfff3105dc655a4f5b300fe.jpg
113	115	static/images/base/products/b6d61813547e606d0e705772a325ca93.jpg
117	119	static/images/base/products/f0857d28f4dfbfa3cf25410345559763.jpg
121	123	static/images/base/products/00c336fc5fe87b6e35a72b193d6cd2ab.jpg
124	126	static/images/base/products/6cac716a85a3efe0f6bbccb94c838dc6.png
128	130	static/images/base/products/e4a9ba1d42a00f7be3f7d4f110c24f2a.jpg
131	133	static/images/base/products/f815bc362fb4ad21300e9168b97f269c.jpg
38	40	static/images/base/products/af69a3ee9e8092bb0202267c6d64a813.jpg
57	59	static/images/base/products/51daec79c1c71accd0202a93b591bc86.jpg
76	78	static/images/base/products/8b02fe82c0504cda975aca2932d75685.jpg
89	91	static/images/base/products/eb1da627000d62f63dfbf982be1d4939.jpg
108	110	static/images/base/products/036890c02c19447bca59739eeda1959e.jpg
127	129	static/images/base/products/c05160e80306ec66f1e63d5f4908afc5.jpg
135	137	static/images/base/products/721c9599d999201cc640c1ee43466280.jpg
139	141	static/images/base/products/63c2dc0e00ea0a7bb219e9d234b0375f.jpg
142	144	static/images/base/products/186f02db0b50a18b947e075edc7b3e9f.jpg
145	147	static/images/base/products/398fe74bb69a59d37886bddec33c23b7.jpg
148	150	static/images/base/products/b229bf3b3588321ffc214edc27927bf3.jpg
151	153	static/images/base/products/d47c509b252bab9508f20f953f4bef29.jpg
154	156	static/images/base/products/ff0452f422b78124eec829ecf681efa6.jpg
157	159	static/images/base/products/1f33c76398c1d3ab40ca9a97fae50bc7.jpg
351	353	static/images/base/products/b00106e247eb4dbbc77e429c5fb31035.webp
352	354	static/images/base/products/7b6ae1a4d6301253764e52432d91a796.webp
354	356	static/images/base/products/5cd3bb23818c4b3603ebc4c6f54db425.webp
355	357	static/images/base/products/da5c5a42ecd4f3545ffa3cec2c1e0b43.jpg
357	359	static/images/base/products/0edad3f0456c219f817bb780475ff920.jpg
358	360	static/images/base/products/b3f5abff2c56e613972833ff3199f486.jpg
360	362	static/images/base/products/e680bcd6048a2e52d2aa7416ed5568b8.jpg
361	363	static/images/base/products/35c8f100204c1c46c7fa44f0f77b23cd.jpg
363	365	static/images/base/products/5791a1a3ecd474fc6fd867f5e5fc3e2d.jpg
364	366	static/images/base/products/9244680380714b7ad4e609abca7c2570.jpg
366	368	static/images/base/products/e85c94f6ebb4496333c34b4ad4a8baad.jpg
367	369	static/images/base/products/00923cad8f886909d0275e3c8165fc93.jpg
369	371	static/images/base/products/8de19cea282e78b37ace76f606d735d9.jpg
370	372	static/images/base/products/f086d2824d8485f8f7a95c0879c740a9.jpg
372	374	static/images/base/products/ef1d19b447caa6020f81b2938164c753.jpg
373	375	static/images/base/products/0e624a7cadbac3ef4db704f802b3ab6b.jpg
375	377	static/images/base/products/4adef58035d031199d08b6c028fea2df.jpg
376	378	static/images/base/products/d71daa54fdd26e73466e7b65bff2ceb0.jpg
378	380	static/images/base/products/1692dc0b9b510c071a808c8fe8a1214f.jpg
379	381	static/images/base/products/a1399ac8f8d1de717ceb96d3418266ad.jpg
381	383	static/images/base/products/f9cd729c1f76a3f7146f33affb2b9416.jpg
382	384	static/images/base/products/c848f04d5d56c36051cb0396ee4dd4e5.jpg
384	386	static/images/base/products/d57cfb0fd6f24ae86bf6d300318eb400.jpg
385	387	static/images/base/products/6fbe781bc7f34012ab6ed39387fc2b09.jpg
387	389	static/images/base/products/34f10dff7d440464dd3ed6c3cff3a377.jpg
160	162	static/images/base/products/1f13a9479265ff77f7c2d42017d22256.jpg
163	165	static/images/base/products/d827ff4b22b3a9364a8a1b7dc7d6b6fe.jpg
166	168	static/images/base/products/5f5adb4282204d7e58864845714f761f.jpg
169	171	static/images/base/products/2d9c413d5a6151cee7ac39e374bc3cfb.jpg
172	174	static/images/base/products/058d85cd96c398c91f0c496d8ca85c54.jpg
176	178	static/images/base/products/be8a849f99944f0a9257ff945ba4da03.jpg
179	181	static/images/base/products/5c9147ae8191844cce6061d6266678dc.jpg
182	184	static/images/base/products/149e8b3f788bdbba4cff102d4ded8ae2.jpg
185	187	static/images/base/products/c1ec8357afdd3cde99cb50a009816890.jpg
188	190	static/images/base/products/540683b5c034045ad499749af4e55fad.jpg
206	208	static/images/base/products/e60ac83bda473cb7d0a7166b45148469.jpg
191	193	static/images/base/products/90c2ae04e4d1a9536b4291867b02b269.jpg
194	196	static/images/base/products/d83a840cae20df19c694039fb6c98165.jpg
197	199	static/images/base/products/da28e3e6e9309b7f57d4589e618d281c.jpg
199	201	static/images/base/products/41e7e17aeb42cafe55f6fb402c9d49bf.jpg
202	204	static/images/base/products/62484072ea19495f3bfebe987b0cf08f.jpg
207	209	static/images/base/products/e653df27ba374132198069ce9fa811bf.jpg
210	212	static/images/base/products/f0f2f9f801036d5cc066f5804a4b271c.jpg
213	215	static/images/base/products/958da6ea3bea03456d696c7364007706.jpg
216	218	static/images/base/products/b44bd3b106e69e08c0dd8aad51504aa5.jpg
219	221	static/images/base/products/91283339ee6a72dab5f854ae7c9e2faa.jpg
224	226	static/images/base/products/3f85193675bb739d2ee64855b044a6f1.jpg
228	230	static/images/base/products/d5e49f0cd867af7d5d55a7a2e00809dd.jpg
232	234	static/images/base/products/ea578395ca4c94bfc96e033720e1f873.jpg
222	224	static/images/base/products/7f9e4ab88474903dfd91f7e7039878c5.jpg
225	227	static/images/base/products/402378a236ae9ffe0de7e8f35d76faf1.jpg
236	238	static/images/base/products/20fdee6317b9855581dee3d8a50cffb5.jpg
239	241	static/images/base/products/0b1f0d688bd88569f09e9e9fcc027611.jpg
244	246	static/images/base/products/67c90564c6037afbe4cb96ca8d71026c.jpg
247	249	static/images/base/products/8fad0a4eb840b0fd158fc564ddba7c8d.jpg
250	252	static/images/base/products/d230440bb9ad2000d89e363d0028d41b.jpg
263	265	static/images/base/products/99f7581c48973d6ce18835f9223788c4.jpg
266	268	static/images/base/products/9dfb4f16aafa93132498b2671e054ec9.jpg
269	271	static/images/base/products/03fd96d7b5a4727b41488432add4c543.webp
272	274	static/images/base/products/22d1624ac450b536a3f5d9c77de8e7f0.webp
275	277	static/images/base/products/92052dc604c27328ff47db3afd0266a1.webp
278	280	static/images/base/products/80be9006ec1fe70153bce07ef15a88e0.webp
281	283	static/images/base/products/67a5dec25c247fedffb6a4a10e753013.webp
284	286	static/images/base/products/23a686459ad416e2b21495e9ecf2def0.webp
287	289	static/images/base/products/9dbf89d325b62f842df1f51863d85129.webp
290	292	static/images/base/products/75e9512a0189a6062deaa0117682bf0a.webp
293	295	static/images/base/products/82cf78f367eb0e09cc7814ea74b80832.webp
296	298	static/images/base/products/a577e517a54ac113562a1298506befd9.webp
299	301	static/images/base/products/dbb49431d3fd869a5ef294d4ad3240b9.webp
302	304	static/images/base/products/1f566a52bc1fdb83bca8996255e99196.webp
305	307	static/images/base/products/456d42da57831b58544f18dc5ec5cd6e.webp
308	310	static/images/base/products/e0c90c4c88f036a9793befb781d0a8e8.webp
311	313	static/images/base/products/54fdc9676bb7fdf810260b36235169c3.webp
314	316	static/images/base/products/e48d8dc35c18f3232957e38999b18cb9.webp
317	319	static/images/base/products/aa3f489e67c3be8ea806adb8441c2db9.webp
320	322	static/images/base/products/37ce1ac0989b5d1cd6af1354feaf6ddb.webp
323	325	static/images/base/products/b9b4ad4e14fe36beee4814e54a398244.webp
326	328	static/images/base/products/df1f7a485a9e8084a9ee0b93f71958ac.webp
329	331	static/images/base/products/5c1c0682f5eaafd908d58907634f8651.webp
332	334	static/images/base/products/18ef57fac80e11410b14a5c5e1b76ba9.webp
335	337	static/images/base/products/ea7bcd1ab02b336e49a9e855f61ab1b9.webp
338	340	static/images/base/products/0dc7335b2381d14275bc2eccffd2a13d.webp
341	343	static/images/base/products/73108dad5d66c7611938723b4c936fcb.webp
344	346	static/images/base/products/779baf64598ddcbd4bf4f45e3c930cbd.webp
347	349	static/images/base/products/da1d7bf6fbf2f0b428e2ea7baa623e4a.webp
350	352	static/images/base/products/16a2e76286124cc844a6e9c896a3e8b5.webp
353	355	static/images/base/products/388a7083fc79fdd5bfea5734c49e21de.webp
356	358	static/images/base/products/5e175f092276afe4c1878e09cab077f6.jpg
359	361	static/images/base/products/9da4e4a1224d103beca30ce90be2aeea.jpg
362	364	static/images/base/products/a0991c09d05ca421036b8e49fd5d6f47.jpg
365	367	static/images/base/products/893e9dc01ec80850d11e86e06249a505.jpg
368	370	static/images/base/products/af7bc64303534e65326f0c20ad6cbcc5.jpg
371	373	static/images/base/products/a3dcd0095d4d0ad3aeeab45d3d7d4ae7.jpg
374	376	static/images/base/products/17d52b008bed426f29cf461a3d12ff38.jpg
377	379	static/images/base/products/2dc1f7d71d11733dbd069f9772ce2d9f.jpg
380	382	static/images/base/products/c32fd87d619bc8626b37a884d9c61908.jpg
383	385	static/images/base/products/cf1abb1e9a48fd44b524b955ab361dd8.jpg
386	388	static/images/base/products/670e3d1becae51116502b9b03175b175.jpg
\.


--
-- Data for Name: tile_sizes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tile_sizes (length, height, width, id) FROM stdin;
100.00	4.00	400.00	1
300.00	9.00	600.00	2
400.00	9.00	400.00	3
60.00	9.00	90.00	4
600.00	9.00	900.00	5
600.00	9.00	600.00	6
250.00	8.00	500.00	7
600.00	10.00	600.00	8
600.00	11.00	1200.00	9
600.00	11.00	600.00	10
327.00	8.00	327.00	11
200.00	11.00	1200.00	12
600.00	8.00	600.00	13
280.00	8.00	400.00	14
600.00	10.00	1200.00	15
600.00	9.00	1200.00	16
250.00	7.00	350.00	17
\.


--
-- Data for Name: tile_surface; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tile_surface (name) FROM stdin;
рельеф
под дерево
бетон
под камень
мрамор
матовая
матовый
полированный
карвинг
\.


--
-- Name: boxes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.boxes_id_seq', 19, true);


--
-- Name: catalog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_id_seq', 389, true);


--
-- Name: collections_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.collections_id_seq', 70, true);


--
-- Name: tile_images_image_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tile_images_image_id_seq', 387, true);


--
-- Name: tile_sizes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tile_sizes_id_seq', 17, true);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (username);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: boxes boxes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.boxes
    ADD CONSTRAINT boxes_pkey PRIMARY KEY (id);


--
-- Name: catalog catalog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog
    ADD CONSTRAINT catalog_pkey PRIMARY KEY (id);


--
-- Name: collection_category collection_id_category_name_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collection_category
    ADD CONSTRAINT collection_id_category_name_pk PRIMARY KEY (collection_id, category_name);


--
-- Name: collections collections_image_path_key1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_image_path_key1 UNIQUE (image_path);


--
-- Name: collections collections_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_name_key UNIQUE (name);


--
-- Name: collections collections_pkey1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_pkey1 PRIMARY KEY (id);


--
-- Name: producers producers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producers
    ADD CONSTRAINT producers_pkey PRIMARY KEY (name);


--
-- Name: slugs slugs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slugs
    ADD CONSTRAINT slugs_pkey PRIMARY KEY (name, slug);


--
-- Name: tile_colors tile_colors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tile_colors
    ADD CONSTRAINT tile_colors_pkey PRIMARY KEY (color_name, feature_name);


--
-- Name: tile_images tile_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tile_images
    ADD CONSTRAINT tile_images_pkey PRIMARY KEY (image_id);


--
-- Name: tile_sizes tile_sizes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tile_sizes
    ADD CONSTRAINT tile_sizes_pkey PRIMARY KEY (id);


--
-- Name: tile_surface tile_surface_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tile_surface
    ADD CONSTRAINT tile_surface_pkey PRIMARY KEY (name);


--
-- Name: categories types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT types_pkey PRIMARY KEY (name);


--
-- Name: boxes uq_boxes_weight_area; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.boxes
    ADD CONSTRAINT uq_boxes_weight_area UNIQUE (weight, area);


--
-- Name: tile_sizes uq_tile_sizes_length_width_height; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tile_sizes
    ADD CONSTRAINT uq_tile_sizes_length_width_height UNIQUE (length, width, height);


--
-- Name: catalog catalog_color_name_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog
    ADD CONSTRAINT catalog_color_name_fkey FOREIGN KEY (color_name, feature_name) REFERENCES public.tile_colors(color_name, feature_name);


--
-- Name: catalog catalog_producer_name_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog
    ADD CONSTRAINT catalog_producer_name_fkey FOREIGN KEY (producer_name) REFERENCES public.producers(name);


--
-- Name: catalog catalog_surface_name_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog
    ADD CONSTRAINT catalog_surface_name_fkey FOREIGN KEY (surface_name) REFERENCES public.tile_surface(name);


--
-- Name: catalog fk_catalog_boxes_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog
    ADD CONSTRAINT fk_catalog_boxes_id FOREIGN KEY (box_id) REFERENCES public.boxes(id);


--
-- Name: catalog fk_catalog_tile_sizes_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog
    ADD CONSTRAINT fk_catalog_tile_sizes_id FOREIGN KEY (size_id) REFERENCES public.tile_sizes(id);


--
-- Name: catalog fk_catalog_types; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog
    ADD CONSTRAINT fk_catalog_types FOREIGN KEY (category_name) REFERENCES public.categories(name);


--
-- Name: collection_category fk_collection_category_category; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collection_category
    ADD CONSTRAINT fk_collection_category_category FOREIGN KEY (category_name) REFERENCES public.categories(name) ON DELETE CASCADE;


--
-- Name: collection_category fk_collection_category_collection; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collection_category
    ADD CONSTRAINT fk_collection_category_collection FOREIGN KEY (collection_id) REFERENCES public.collections(id) ON DELETE CASCADE;


--
-- Name: tile_images tile_images_tile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tile_images
    ADD CONSTRAINT tile_images_tile_id_fkey FOREIGN KEY (tile_id) REFERENCES public.catalog(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict jBOvHjcL1iH3gMhX7tGKfAF8wRIrS8OD3b6zXjMHv9Uy6jOEmkldRQuf2W0Brci

